### ISSUE TITLE
Employee Menu and Search screen

### ISSUE THREAD

**Issue by procupid** [kanwalnainsingh/OpenDesk#107]
The Designs are ready for both screens. Both the mobile version and Desktop version designs are attached as the screens should be responsive.

### MENU SCREENS

MOBILE VERSION >
![Employee page](https://user-images.githubusercontent.com/67896359/100636940-47392c80-3358-11eb-9deb-3ac2937eb159.png)

DESKTOP VERSION> 
This screen will work as an overlay to the home screen
![Landing Page](https://user-images.githubusercontent.com/67896359/100636930-443e3c00-3358-11eb-8227-f04adf0ade3d.png)

### SEARCH SCREENS

MOBILE VERSION >
![Employee page-1](https://user-images.githubusercontent.com/67896359/100636943-47d1c300-3358-11eb-8d67-20ca4b103a8a.png)

DESKTOP VERSION >
![Landing Page-1](https://user-images.githubusercontent.com/67896359/100636937-46a09600-3358-11eb-83b1-843c04a84c95.png)

**Comment by alebricio** [comment]
Hello! This looks great. I'll contact you on Slack for more details if it's okay!

**Comment by alebricio** [comment]
Working on this! 👍

**Comment by kanwalnainsingh** [comment]
@alebricio changes looks perfect. I have merged your PR

**Comment by kanwalnainsingh** [comment]
Changes merged.
