### ISSUE TITLE
Organization Employees Page

### ISSUE THREAD

**Issue by procupid** [kanwalnainsingh/OpenDesk#118]
### DESKTOP VERSION
![Landing Page](https://user-images.githubusercontent.com/67896359/101247732-20586d00-3741-11eb-8a07-9f70db20ab59.png)

### MOBILE VERSION
![Employee page](https://user-images.githubusercontent.com/67896359/101247735-22223080-3741-11eb-9502-b61cb8e3ce77.png)
![Employee page-1](https://user-images.githubusercontent.com/67896359/101247736-22bac700-3741-11eb-80d0-ae28362f5282.png)

for the logo use SVG instead of png

**Comment by mayralgr** [comment]
HI @kanwalnainsingh @procupid I would like to work on this issue, do I need more information in addition to the screens?
Thank you!

**Comment by kanwalnainsingh** [comment]
@mayralgr this should be enough refer them existing code and figma for more details on design. Let me know if you need anything else

**Comment by mayralgr** [comment]
@kanwalnainsingh should we open the issue again until it is finished? 😊

**Comment by kanwalnainsingh** [comment]
Sure, I have updated the issue. Feel free to create another issue for this. You can also IM on slack or join front end team WhatsApp group if you would like. https://chat.whatsapp.com/EdNOIXay2CcITZFOGwFD4t

**Comment by mayralgr** [comment]
@kanwalnainsingh will do. I’ll open another pr with the rest. Can this issue be assigned ? 😊
