### ISSUE TITLE
Site Page (Organization)

### ISSUE THREAD

**Issue by procupid** [kanwalnainsingh/OpenDesk#119]
### **[FIGMA FILE](https://www.figma.com/file/NihC7mPNWDLTTfOyKpChhN/BookOpendesk?node-id=3%3A1069)** 
(Contains Design)

### DESKTOP VERSION
![Landing Page](https://user-images.githubusercontent.com/67896359/101247921-3a467f80-3742-11eb-9766-f63541ffef55.png)

### MOBILE VERSION
![Employee page](https://user-images.githubusercontent.com/67896359/101247922-3d417000-3742-11eb-98ea-82b99160b271.png)
![Employee page-1](https://user-images.githubusercontent.com/67896359/101247923-3dda0680-3742-11eb-97d5-e7324553edfc.png)

**Comment by mayralgr** [comment]
I'll work on this one, I'll raise a pr with the page.
