### ISSUE TITLE
Organization Account and search screen

### ISSUE THREAD

**Issue by procupid** [kanwalnainsingh/OpenDesk#122]
### **[FIGMA FILE](https://www.figma.com/file/NihC7mPNWDLTTfOyKpChhN/BookOpendesk?node-id=7%3A21672)**
(contains design)

### ACCOUNT SCREEN

Desktop Version:
![Landing Page](https://user-images.githubusercontent.com/67896359/101262071-d6cc4a00-3761-11eb-8b15-6c17e37ba27b.png)

Mobile Version:
![Employee page](https://user-images.githubusercontent.com/67896359/101262074-da5fd100-3761-11eb-88cc-04d6b2a93618.png)

### SEARCH SCREEN

Desktop Version:
![Landing Page-1](https://user-images.githubusercontent.com/67896359/101262073-d9c73a80-3761-11eb-924b-74183407df41.png)

Mobile Version:
![Employee page-1](https://user-images.githubusercontent.com/67896359/101262075-db90fe00-3761-11eb-836e-3abbfb84d5fd.png)

**Comment by devjuliet** [comment]
Hi! @kanwalnainsingh I would like to work on this issue if that is okay. Do I need some other specifications to start working?

**Comment by kanwalnainsingh** [comment]
@devjuliet yes feel free to pick this one, I will assign.
