### ISSUE TITLE
Add Site screen

### ISSUE THREAD

**Issue by procupid** [kanwalnainsingh/OpenDesk#123]
### **[FIGMA FILE](https://www.figma.com/file/NihC7mPNWDLTTfOyKpChhN/BookOpendesk?node-id=3%3A1816)** 
(containing the design)

### DESKTOP VERSION
![Landing Page](https://user-images.githubusercontent.com/67896359/101262251-2d865380-3763-11eb-9c98-4d10d3823855.png)

### MOBILE VERSION
![Employee page](https://user-images.githubusercontent.com/67896359/101262253-30814400-3763-11eb-94e7-8b2f7d72d987.png)

**Comment by alebricio** [comment]
Looks great! I'd like to work on this if it's okay.
