### ISSUE TITLE
Project Structure front end using ReactJS or ReactNative

### ISSUE THREAD

**Issue by kanwalnainsingh** [kanwalnainsingh/OpenDesk#14]
Project structure with React JS, this should include package manager using npm and test case framework like Jest.
Add appropriate structure for CSS as well.
This should include code package structure.
Refer below link for inspiration https://www.simform.com/react-architecture-best-practices/?fbclid=IwAR3p77RG6h7kUHqcuTwnR8QUDp0fSdvKKLAeXjb-s9SCcyT_jcudLfv8dhA

**Comment by zeus0123** [comment]
Can we use redux saga for state management and styled components for css

**Comment by kanwalnainsingh** [comment]
> Can we use redux saga for state management and styled components for css

Sure, feel free to use.
