### ISSUE TITLE
New Site UI calling backend to save a new site.

### ISSUE THREAD

**Issue by kanwalnainsingh** [kanwalnainsingh/OpenDesk#141]
Below is the new UI for new site addition.
![image](https://user-images.githubusercontent.com/1909626/103015247-12d71b80-4566-11eb-9dcc-066d4ff099b6.png)
https://www.bookopendesk.com/newsite
Save button in above UI should be able to call organisation service, swagger linke below.
https://www.bookopendesk.com/api/organisation-service/swagger-ui/index.html?configUrl=/api/organisation-service/v3/api-docs/swagger-config

Similar code is already written in old UI here https://www.bookopendesk.com/organisation

**Comment by alebricio** [comment]
Working on this! 👍
