### ISSUE TITLE
Front end architecture diagram and library finalisation.

### ISSUE THREAD

**Issue by kanwalnainsingh** [kanwalnainsingh/OpenDesk#15]
**What we need?**

- Project Structure diagram.
- Separation of concern for for various code layer is crucial to maintain project in future.
- Don’t overthink the application structure and avoid using too many nested files and folders 
- Divide logical components like, datastore, react components, events and dom.
- Each component should be testable.
- Structure to include where test case will be added.

Below article for inspiration https://www.simform.com/react-architecture-best-practices/

**Comment by SaswataRakshit** [comment]
https://github.com/SaswataRakshit/OpenDesk/tree/Initial_Planning/docs/planning

Added flow diagram for Organization service.

**Comment by kanwalnainsingh** [comment]
Thanks a lot @SaswataRakshit  for you contribution, welcome to the team. Really liked your thought process. 
In order to raise a pull request for your change, please refer https://jarv.is/notes/how-to-pull-request-fork-github/  I will be happy to share review comments on your pull request to keep the issue clean for others to view.

**Comment by SaswataRakshit** [comment]
As per latest disscussion, I structured the code.
https://github.com/SaswataRakshit/OpenDesk/tree/Initial_Planning/docs/planning

**Comment by kanwalnainsingh** [comment]
> As per latest disscussion, I structured the code.
> https://github.com/SaswataRakshit/OpenDesk/tree/Initial_Planning/docs/planning

Looks good @SaswataRakshit  please raise a pull request refer  https://opensource.com/article/19/7/create-pull-request-github and let me know if you face any issue.
