### ISSUE TITLE
API to check if desk is available for booking on a particular date 

### ISSUE THREAD

**Issue by kanwalnainsingh** [kanwalnainsingh/OpenDesk#60]
## NEW API:
/api/desk-service/availability
POST

requestBody:
{
"orgId": "string"
"floorId":"string"
"requestDate": "string" dd/MM/yyyy

} 

Action: api will call booking-service- get all the booking for particular data on orgId and floorId. API will return a desk which is not already booked in booking service.

**Comment by devjuliet** [comment]
Hi! Can you help me with some specifications to start with this issue. It is going to be another endpoint? What would be the payload like? Thanks! @kanwalnainsingh

**Comment by kanwalnainsingh** [comment]
@devjuliet I have added some details, in order to check how api is called from one service to another refer organisation-service where booking-service /health api is called. refer swagger here https://www.bookopendesk.com/api/organisation-service/swagger-ui/index.html?configUrl=/api/organisation-service/v3/api-docs/swagger-config#/organisation-controller/geBookingServiceHealth

**Comment by devjuliet** [comment]
#116 PR is now available @kanwalnainsingh ! If it needs changes, I am open to feedback etc! 😄
