### ISSUE TITLE
API to get all desk for particular organisation, site and floor.

### ISSUE THREAD

**Issue by kanwalnainsingh** [kanwalnainsingh/OpenDesk#62]
# Requirement 

## New API
Microservice: desk-service
Code_Base: https://github.com/kanwalnainsingh/OpenDesk/tree/main/code_base/micro-services/desk-service 
Method Type: GET
Path: /desk/{orgId}/{siteId}/{floorId} 

### What will API do?

API will fetch list of all the desk for particular organisation, site and floor. 

### Acceptance criteria.

1. Given  {orgId} {siteId} {floorId} has corresponding data API should return List<Desk> for requested data with HTTP Status 200. 
2. Given {orgId} {siteId} {floorId} does not have corresponding data API should return  empty List<Desk> with HTTP Status 204 No Content. 
3. Given any of {orgId} {siteId} {floorId} is missing API should return  empty List<Desk> with HTTP Status 204 No Content. 

Note: Create relevant data to test using swagger api at http://localhost:{port}/swagger-ui.html

**Comment by chetanchilhate** [comment]
@kanwalnainsingh I would like to work on this. I can see endpoints are there only it always returning 200 status always with or without the data

**Comment by kanwalnainsingh** [comment]
@chetanchilhate feel free to fix the behaviour

**Comment by chetanchilhate** [comment]
@kanwalnainsingh colud assign the issue to me or its not nesssasary

**Comment by kanwalnainsingh** [comment]
@chetanchilhate issue assigned. feel free to ask question here or on slack https://join.slack.com/t/opendeskworkspace/shared_invite/zt-jf6wxjc3-aj5SF9S6t~VSJiRswQwXbw
