### ISSUE TITLE
UI UX Design for Open Desk Start

### ISSUE THREAD

**Issue by kanwalnainsingh** [kanwalnainsingh/OpenDesk#64]

**Comment by procupid** [comment]
Added Figma file containing designs for both mobile and web versions.
https://github.com/procupid/OpenDesk.git

**Comment by procupid** [comment]
Figma File: https://www.figma.com/file/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=101%3A689
Mobile version prototype: https://www.figma.com/proto/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=10%3A46&scaling=min-zoom
Desktop version prototype:  https://www.figma.com/proto/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=206%3A2729&scaling=scale-down
