### ISSUE TITLE
Frontend page of Onboarding Organization page

### ISSUE THREAD

**Issue by SaswataRakshit** [kanwalnainsingh/OpenDesk#71]
As a part of this story, UI of Organization onboarding will be done.
![onboarding](https://user-images.githubusercontent.com/46588264/99423213-58307980-2926-11eb-86a8-9ae3059e9c41.jpg)

**Comment by kanwalnainsingh** [comment]
Please follow below structure on design for react components. 
<Site>
   <SiteDetails>
      <Location />
      <SiteName />
   </SiteDetails>
   <Floor>
      <FloorDetails>
         <FloorName />
         <DeskDetails>
            <DeskCount />
            <BusyDesk />
            <DeskPlan />
         </DeskDetails>
      </FloorDetails>
   </Floor>
</Site>
