### ISSUE TITLE
API: Organisation Site Registration.

### ISSUE THREAD

**Issue by kanwalnainsingh** [kanwalnainsingh/OpenDesk#73]
## Requirement 
Update is required in existing API as per new design. Remove data fields that are not part of below contract.

### Existing API
Method Type: POST
URL: organisation-service/organisation
Request Body:

```
{
  "orgId": "string",
  "companyName": "string",
  "location": {
    "address": "string",
    "geoLocation": "string"
  },
  "sites": [
    {
      "name": "string",
      "floors": [
        {
          "name": "string",
          "openDesk": "string",
          
        }
      ]
    }
  ]
}
```

**Comment by devjuliet** [comment]
Hello! I would like to work on this issue if that is okay :)

**Comment by kanwalnainsingh** [comment]
Hi @devjuliet, Welcome 🙏 
We there is some progress already already made on this, join slack, setup code base. Will assign something fresh. https://www.bookopendesk.com

**Comment by devjuliet** [comment]
Great!! Joining now
