### ISSUE TITLE
Create an API in booking service to fetch booking details based on the employee id.

### ISSUE THREAD

**Issue by ryagnaguru** [kanwalnainsingh/OpenDesk#74]
Requirement:

This API in booking service that takes employee id as parameter is used to fetch all the booking details associated to the id.

API:

CODE_BASE: code_base/microservices/booking-service
API: /booking/employee/{empId}
Method Type: GET

Note: You might need to create data in micro-service via swagger api. Use below url
http://localhost:{port}/api/bookings-service/swagger-ui.html

**Comment by kanwalnainsingh** [comment]
PR merged.
