### ISSUE TITLE
Work-In-Progress Page (Responsive)

### ISSUE THREAD

**Issue by procupid** [kanwalnainsingh/OpenDesk#78]
For the time period, our service is not ready to launch, we would create a work-in-progress page.

What would it contain?

- Notice for work-in-progress
- About the project
- Invitation for people to contribute

The design should be responsive.

I have created designs for the above pages

![Landing Page (3)](https://user-images.githubusercontent.com/67896359/99792758-90fe6780-2b4d-11eb-9a56-effb47c66898.png)
^ Desktop Version

<img width="411" alt="Work In Progress Expanded" src="https://user-images.githubusercontent.com/67896359/99792843-b2f7ea00-2b4d-11eb-8c31-7392b2c43e8a.png">
^ Mobile Version

Here is the link to the Figma FIle: https://www.figma.com/file/ZokvwLKeLxgqGnidqQ2NAW/Work-in-Progress-Opendesk

**Comment by pebriancharliady** [comment]
Sorry i'm really new to open sourcing, how can i assign to this issue ?

**Comment by kanwalnainsingh** [comment]
@pebriancharliady I will assign this you.

**Comment by kanwalnainsingh** [comment]
@pebriancharliady issue assigned, let us know if you need help

**Comment by pebriancharliady** [comment]
@kanwalnainsingh ok thank you very much
