### ISSUE TITLE
Landing Page and How-It-Works Pages

### ISSUE THREAD

**Issue by procupid** [kanwalnainsingh/OpenDesk#85]
This Issue is to develop the designs for the following pages. 

### - Landing Page

![Landing Page (4)](https://user-images.githubusercontent.com/67896359/99883747-68f72d00-2c4f-11eb-9882-60b26c36b854.png)

Desktop Verson ^^^

![Landing Page (5)](https://user-images.githubusercontent.com/67896359/99883745-65fc3c80-2c4f-11eb-9c00-e5590385b45f.png)

Mobile Version ^^

**I HAVE PROVIDED PREVIEW JUST FOR THE LANDING PAGE , for others please check the figma file.**

### - Organization Selection screen

All pages will be responsive thus I have designed two versions of each page; for both desktop and mobile.

### **[Figma Design File](https://www.figma.com/file/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=593%3A26420)**
(If you are a designer and would like to improve anything, please ping me so as to gain editing access)

**[Mobile Prototype](https://www.figma.com/proto/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=301%3A7274&scaling=min-zoom)**

**[Desktop Prototype](https://www.figma.com/proto/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=206%3A2729&scaling=min-zoom)**

**Comment by pebriancharliady** [comment]
working on this atm

**Comment by procupid** [comment]
There have been some updates to the design

Please refer to this **[Figma File](https://www.figma.com/file/NihC7mPNWDLTTfOyKpChhN/BookOpendesk?node-id=1%3A5980)**

### Some Previews

![How it works 10](https://user-images.githubusercontent.com/67896359/100626728-2d91e800-334c-11eb-810d-694d69f81cc6.png)
![About Us](https://user-images.githubusercontent.com/67896359/100626742-308cd880-334c-11eb-9a87-a7c388da1041.png)
