### ISSUE TITLE
Employee Booking Screen

### ISSUE THREAD

**Issue by kanwalnainsingh** [kanwalnainsingh/OpenDesk#94]
### [Figma File]
https://www.figma.com/file/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=683%3A548 
The designs are ready and contain both desktop and mobile versions as all screens should be responsive.

This issue is for the development of following screens:

- Booking Screen
- Menu
### [Figma File] UX design for images style details.
https://www.figma.com/file/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=683%3A548 

Here is the preview for the home screen:(for the rest of the design please check out the figma file)

**MOBILE VERSION**

![image](https://user-images.githubusercontent.com/1909626/100094861-a93cf200-2e7f-11eb-9d75-624e50178e42.png)
![image](https://user-images.githubusercontent.com/1909626/100094874-af32d300-2e7f-11eb-9f56-e174cad78faa.png)
![image](https://user-images.githubusercontent.com/1909626/100094888-b3f78700-2e7f-11eb-8666-e33db8effe61.png)
![image](https://user-images.githubusercontent.com/1909626/100094901-b8bc3b00-2e7f-11eb-9dbf-d0bb221f06a0.png)
![image](https://user-images.githubusercontent.com/1909626/100094918-bf4ab280-2e7f-11eb-8210-ddd39a9cdc50.png)
![image](https://user-images.githubusercontent.com/1909626/100094926-c376d000-2e7f-11eb-8a1a-7f117a19e9c3.png)
![image](https://user-images.githubusercontent.com/1909626/100094933-c70a5700-2e7f-11eb-9d4c-82c938de2b27.png)

### [Figma File]
https://www.figma.com/file/s9ZDbblJ9wnfisoOZI7kTj/bookopendesk?node-id=683%3A548

**Comment by Elvis020** [comment]
Working on it

**Comment by procupid** [comment]
There have been some text changes in the design.

please refer to the **[NEW FIGMA FILE ](https://www.figma.com/file/NihC7mPNWDLTTfOyKpChhN/BookOpendesk?node-id=2%3A3566)**

**Comment by kanwalnainsingh** [comment]
@procupid can you update the screenshot above one I attached are too big, also add desktop screenshot

**Comment by Elvis020** [comment]
Yhs I think he screenshots are too big I always have to zoom out to scroll faster, pls reduce the size if possible @procupid

**Comment by alebricio** [comment]
Working on this! 👍
